package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

// configFileName is the name of the config file discovered and generated by the
// tool, in the current directory or the user's home directory.
const configFileName = ".contributors.yaml"

// defaultConfig is the annotated template written by `contributors config`.
const defaultConfig = `# contributors configuration
# See ` + "`contributors --help`" + ` for details on each option.

# Repositories to analyze. Each entry is either a clone URL (https://…, git@…,
# or a path ending in .git) or a local path relative to this config file.
# Remote repositories are cloned into a per-user cache and refreshed on each run.
# When set, data is aggregated across all repositories (a global view plus one
# per repository). A path argument on the command line overrides this list.
repositories: []
# repositories:
#   - .
#   - ../sibling-repo
#   - https://github.com/owner/project.git
#   - git@github.com:owner/other.git

# First day of the calendar week: monday or sunday.
week-start: monday

# Ignore and overwrite the on-disk cache (force a full rescan).
no-cache: false

# Contributor names or emails whose commits are excluded from all statistics.
ignore: []
# ignore:
#   - noreply@github.com
#   - "CI Bot"

# Ignore all changes to Markdown files (*.md) and docs/ folders.
exclude-docs: false

# Limit the history window. When set, only commits within the last N months
# from the HEAD commit date are considered. This is useful for large repositories
# where the full history would take too long to scan.
# time-window: 6

# Limit the history to the most recent N commits. When combined with
# time-window, both constraints apply.
# commit-window: 1000

# Aggregate several git author identities that belong to the same person into a
# single contributor. A commit matches an entry when its author email matches
# one of emails or its author name matches one of usernames. Both are regular
# expressions matched case-insensitively (handy for bots), and matching commits
# are attributed to display-name. display-email is optional and sets the email
# shown for the contributor (otherwise the first email pattern is used).
users: []
# users:
#   - display-name: Jane Doe
#     display-email: jane@example.com
#     emails:
#       - jane@example\.com
#       - jane\.doe@work\.example
#     usernames:
#       - jdoe
#   - display-name: Bots
#     display-email: bots@example.com
#     emails:
#       - .*@users\.noreply\.github\.com
#     usernames:
#       - .*\[bot\]
#       - dependabot
`

// newConfigCmd builds the `config` subcommand, which writes a starter
// .contributors.yaml into the current directory when one does not already exist.
func newConfigCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "config",
		Short: "Generate a starter .contributors.yaml in the current directory",
		Long: "Write a starter .contributors.yaml configuration file (with all " +
			"options and their defaults) into the current directory.\n" +
			"If the file already exists it is left untouched.",
		Args:         cobra.NoArgs,
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			if _, err := os.Stat(configFileName); err == nil {
				fmt.Fprintf(cmd.OutOrStdout(),
					"%s already exists; leaving it untouched.\n", configFileName)
				return nil
			} else if !os.IsNotExist(err) {
				return fmt.Errorf("checking %s: %w", configFileName, err)
			}
			if err := os.WriteFile(configFileName, []byte(defaultConfig), 0o644); err != nil {
				return fmt.Errorf("writing %s: %w", configFileName, err)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Wrote %s\n", configFileName)
			return nil
		},
	}
}
